config/routes.rb
Pistache::Application.routes.draw do

  get "accueil/index"

  resources :responsables
  resources :projets
  resources :taches

  root :to => 'accueil#index'

end

app/models/projet.rb
class Projet < ActiveRecord::Base
  belongs_to :responsable
  has_many :taches, :dependent => :restrict
  attr_accessible :nom, :pause, :responsable_id, :url_info, :url_doc, :date_fin
  
  validates :nom, :presence => true, :uniqueness => true, :length => { :minimum => 3 }
end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  has_many :projets, :dependent => :restrict
  attr_accessible :invalide, :nom
  
  validates :nom, :presence => true, :uniqueness => true, :length => { :minimum => 3 }
end

app/models/tache.rb
class Tache < ActiveRecord::Base
  belongs_to :projet
  attr_accessible :nom, :projet_id, :date_debut, :date_fin, :charge
  
  validates(:nom, :presence => true, :length => { :minimum => 3 })
  validates(:date_debut, :presence => true)
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  def index
    p = Projet.arel_table
    t = Tache.arel_table
    @infos = Projet.where(p[:pause].eq(false).and((p[:date_fin].eq(nil)).or(p[:date_fin].eq(nil)))).includes(:taches).where((t[:date_fin].eq(nil)).or(t[:date_fin].eq(nil)))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projets_controller.rb
# encoding: utf-8

class ProjetsController < ApplicationController
  # GET /projets
  # GET /projets.json
  def index
    # @projets = Projet.all
    t = Projet.arel_table
    @projets_ouverts = Projet.where( (t[:date_fin].eq(nil)).or(t[:date_fin].eq(nil)) )
    @projets_fermes = Projet.where( t[:date_fin].not_eq(nil) )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projets }
    end
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
    @projet = Projet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/new
  # GET /projets/new.json
  def new
    @projet = Projet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @projet }
    end
  end

  # GET /projets/1/edit
  def edit
    @projet = Projet.find(params[:id])
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(params[:projet])

    respond_to do |format|
      if @projet.save
        format.html { redirect_to @projet, notice: "Le projet a été créé avec succès." }
        format.json { render json: @projet, status: :created, location: @projet }
      else
        format.html { render action: "new" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projets/1
  # PUT /projets/1.json
  def update
    @projet = Projet.find(params[:id])

    respond_to do |format|
      if @projet.update_attributes(params[:projet])
        format.html { redirect_to @projet, notice: "Le projet a été mis à jour avec succès." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet = Projet.find(params[:id])
    @projet.destroy

    respond_to do |format|
      format.html { redirect_to projets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/responsables_controller.rb
# encoding: utf-8

class ResponsablesController < ApplicationController
  # GET /responsables
  # GET /responsables.json
  def index
    @responsables = Responsable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @responsables }
    end
  end

  # GET /responsables/1
  # GET /responsables/1.json
  def show
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/new
  # GET /responsables/new.json
  def new
    @responsable = Responsable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @responsable }
    end
  end

  # GET /responsables/1/edit
  def edit
    @responsable = Responsable.find(params[:id])
  end

  # POST /responsables
  # POST /responsables.json
  def create
    @responsable = Responsable.new(params[:responsable])

    respond_to do |format|
      if @responsable.save
        format.html { redirect_to @responsable, notice: "Le responsable a été créé avec succès." }
        format.json { render json: @responsable, status: :created, location: @responsable }
      else
        format.html { render action: "new" }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /responsables/1
  # PUT /responsables/1.json
  def update
    @responsable = Responsable.find(params[:id])

    respond_to do |format|
      if @responsable.update_attributes(params[:responsable])
        format.html { redirect_to @responsable, notice: "Le responsable a été mis à jour avec succès." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsables/1
  # DELETE /responsables/1.json
  def destroy
    @responsable = Responsable.find(params[:id])
    @responsable.destroy

    respond_to do |format|
      format.html { redirect_to responsables_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/taches_controller.rb
# encoding: utf-8

class TachesController < ApplicationController
  # GET /taches
  # GET /taches.json
  def index
    # @taches = Tache.all
    t = Tache.arel_table
    @taches_ouvertes = Tache.where( (t[:date_fin].eq(nil)).or(t[:date_fin].eq(nil)) )
    @taches_fermees = Tache.where( t[:date_fin].not_eq(nil) )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taches }
    end
  end

  # GET /taches/1
  # GET /taches/1.json
  def show
    @tache = Tache.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tache }
    end
  end

  # GET /taches/new
  # GET /taches/new.json
  def new
    @tache = Tache.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tache }
    end
  end

  # GET /taches/1/edit
  def edit
    @tache = Tache.find(params[:id])
  end

  # POST /taches
  # POST /taches.json
  def create
    @tache = Tache.new(params[:tache])

    respond_to do |format|
      if @tache.save
        format.html { redirect_to @tache, notice: "La tâche a été créée avec succès." }
        format.json { render json: @tache, status: :created, location: @tache }
      else
        format.html { render action: "new" }
        format.json { render json: @tache.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taches/1
  # PUT /taches/1.json
  def update
    @tache = Tache.find(params[:id])

    respond_to do |format|
      if @tache.update_attributes(params[:tache])
        format.html { redirect_to @tache, notice: "La tâche a été mise à jour avec succès." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tache.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taches/1
  # DELETE /taches/1.json
  def destroy
    @tache = Tache.find(params[:id])
    @tache.destroy

    respond_to do |format|
      format.html { redirect_to taches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/responsables_helper.rb
module ResponsablesHelper
end

app/helpers/taches_helper.rb
module TachesHelper
end

app/views/accueil/index.html.erb
<div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
    <% @infos.each_with_index do |info, i| %>
        <li<% if i == 0 %> class="active"<% end %>><a href="#l<%= info.id %>" data-toggle="tab"><%= info.nom %></a></li>
    <% end %>
    </ul>

    <div class="tab-content">
	<% @infos.each_with_index do |info, i| %>
      <div class="tab-pane<% if i == 0 %>  active<% end %>" id="l<%= info.id %>">
        <h6 class="page-header">
			Responsable : <%= info.responsable.nom %>
			<% if info.url_info != "" %>
				<%= link_to(info.url_info, {:target => "_blank", :style => "float: right;"}) do %><i class="icon-info-sign"></i><% end %>
			<% end %>
			<% if info.url_info != "" and info.url_doc != "" %><span style="float: right;">&nbsp;&nbsp;/&nbsp;&nbsp;</span><% end %>
			<% if info.url_doc != "" %>
				<%= link_to(info.url_doc, {:target => "_blank", :style => "float: right;"}) do %><i class="icon-book"></i><% end %>
			<% end %>
		</h6>

        <p class="label label-info">Tâches</p>
	    	<table class="table table-striped table-condensed">
	    		<thead>
	    			<tr>
	    				<th></th>
	    				<th>Nom</th>
	    				<th>Date de début</th>
	    				<th>Date de fin</th>
	    				<th>Charge</th>
	    				<th>Action</th>
	    			</tr>
	    		</thead>
	    		<tbody>
				<% if info.taches.count != 0 %>
					<% info.taches.each do |tache| %>
	    			<tr>
	    				<td><%= link_to(edit_tache_path(tache)) do %><i class="icon-pencil"></i><% end %></td>
	    				<td><%= tache.nom %></td>
	    				<td><%= I18n.l(tache.date_debut) %></td>
	    				<td><%= tache.date_fin %></td>
<td><%= select("tache", "charge", [["N/A", 0], ["0,25 j/h", 0.25], ["0,50 j/h", 0.5], ["0,75 j/h", 0.75], ["1,00 j/h", 1], ["1,25 j/h", 1.25], ["1,50 j/h", 1.5], ["1,75 j/h", 1.75], ["2,00 j/h", 2], ["2,25 j/h", 2.25], ["2,50 j/h", 2.5], ["2,75 j/h", 2.75], ["3,00 j/h", 3], ["3,25 j/h", 3.25], ["3,50 j/h", 3.5], ["3,75 j/h", 3.75], ["4,00 j/h", 4], ["4,25 j/h", 4.25], ["4,50 j/h", 4.5], ["4,75 j/h", 4.75], ["5,00 j/h", 5], ["5,25 j/h", 5.25], ["5,50 j/h", 5.5], ["5,75 j/h", 5.75], ["6,00 j/h", 6], ["6,25 j/h", 6.25], ["6,50 j/h", 6.5], ["6,75 j/h", 6.75], ["7,00 j/h", 7], ["7,25 j/h", 7.25], ["7,50 j/h", 7.5], ["7,75 j/h", 7.75], ["8,00 j/h", 8], ["8,25 j/h", 8.25], ["8,50 j/h", 8.5], ["8,75 j/h", 8.75], ["9,00 j/h", 9], ["9,25 j/h", 9.25], ["9,50 j/h", 9.5], ["9,75 j/h", 9.75]]) %></td>
	    				<td><button class="btn" type="submit">Fait !</button></td>
	    			</tr>
					<% end %>
				<% else %>
					<tr><td></td><td class="muted">Aucune tâche</td><td></td><td></td><td></td><td></td></tr>
				<% end %>
	    		</tbody>
	    	</table>
		<br />

      </div>
    <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pistache</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<%= link_to("Pistache", root_path, :class => "brand") %>
				<ul class="nav">
					<li><%= link_to("Nouvelle tâche", new_tache_path) %></li>
				</ul>
				
				<form class="navbar-search pull-left" action="">
					<input type="text" class="search-query span2" placeholder="Recherche (KO)">
				</form>
				
				<ul class="nav pull-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to("Responsables", responsables_path) %></li>
							<li><%= link_to("Projets", projets_path) %></li>
							<li><%= link_to("Tâches", taches_path) %></li>
							<li class="divider"></li>
							<li><%= link_to("Activité #{I18n.l(Time.now.months_ago(1), :format => "%B %Y")} (KO)", root_path) %></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>

<%= yield %>
	</div>

</body>
</html>

app/views/projets/_form.html.erb
<%= form_for(@projet, :html => { :class => "form-horizontal" }) do |f| %>
<fieldset>
  <% if @projet.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@projet.errors.count, "erreur") %> ont été identifiées :</h2>

      <ul>
      <% @projet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label(:nom, :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:nom, :class => "input-xlarge") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:responsable, :class => "control-label") %>
    <div class="controls">
      <%= f.select(:responsable_id, options_from_collection_for_select(Responsable.where("invalide = 'f'").order("nom"), :id, :nom, @projet.responsable_id)) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label("Informations", :class => "control-label") %>
    <div class="controls">
		<div class="input-prepend">
			<span class="add-on">@</span><%= f.url_field(:url_info) %>
		</div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label("Documentation", :class => "control-label") %>
    <div class="controls">
		<div class="input-prepend">
      		<span class="add-on">@</span><%= f.url_field(:url_doc) %>
		</div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:pause, :class => "control-label") %>
    <div class="controls">
      <label class="checkbox">
      <%= f.check_box(:pause) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label("Date de fin", :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:date_fin, :class => "datepicker") %>
    </div>
  </div>

  <div class="form-actions">
    <% if current_page?(:action => "new") %>
      <%= f.submit("Créer le projet", :class => "btn btn-primary") %>
	<% else %>
      <%= f.submit("Mettre à jour le projet", :class => "btn btn-primary") %>
	<% end %>
    <%= link_to("Retour", projets_path, :class => "btn") %>
  </div>
</fieldset>
<% end %>

app/views/projets/edit.html.erb
<h1>Modification</h1>
<br />

<%= render 'form' %>

app/views/projets/index.html.erb
<div class="nouveau">
<%= link_to(new_projet_path, :class => "btn") do %>
  <i class="icon-edit"></i> Nouveau projet
<% end %>
</div>

<br>

<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#ouv" data-toggle="tab">Projets ouverts</a></li>
		<li><a href="#ferm" data-toggle="tab">Projets fermés</a></li>
	</ul>
	
	<div class="tab-content">
		<div class="tab-pane active" id="ouv">
			<!-- Projets ouverts -->
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Responsable</th>
						<th>Actions</th>
					</tr>
				</thead>

				<tbody>
		<% if @projets_ouverts.count != 0 %>
			<% @projets_ouverts.each do |projet| %>
					<tr>
			          <% if projet.pause == true %>
			            <td class="muted"><%= projet.nom %></td>
			            <td class="muted"><%= projet.responsable.nom %></td>
			          <% else %>
			            <td><%= projet.nom %></td>
			            <td><%= projet.responsable.nom %></td>
			          <% end %>
						<td>
							<%= link_to(edit_projet_path(projet)) do %><i class="icon-pencil"></i><% end %>
							<%= link_to(projet, :data => { :confirm => "Cela supprimera définitivement l'entrée !\nÊtes-vous sûr ?" }, :method => :delete) do %><i class="icon-trash"></i><% end %>
						</td>
			  		</tr>
			<% end %>
		<% else %>
					<tr><td class="muted">Aucun Projet</td><td></td><td></td><td></td></tr>
		<% end %>
				</tbody>
			</table>

			<div class="span1 offset10 label label-info" style="text-align:center">Total : <%= @projets_ouverts.count %></div>
		</div>
	
		<div class="tab-pane" id="ferm">
			<!-- Projets fermés -->
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Responsable</th>
						<th>Date de fin</th>
						<th>Actions</th>
					</tr>
				</thead>

				<tbody>
		<% if @projets_fermes.count != 0 %>
			<% @projets_fermes.each do |projet| %>
					<tr>
						<td><%= projet.nom %></td>
			            <td><%= projet.responsable.nom %></td>
						<td><%= I18n.l(projet.date_fin) %></td>
						<td>
							<%= link_to(edit_projet_path(projet)) do %><i class="icon-pencil"></i><% end %>
							<%= link_to(projet, :data => { :confirm => "Cela supprimera définitivement l'entrée !\nÊtes-vous sûr ?" }, :method => :delete) do %><i class="icon-trash"></i><% end %>
						</td>
			  		</tr>
			<% end %>
		<% else %>
					<tr><td class="muted">Aucun Projet</td><td></td><td></td><td></td></tr>
		<% end %>
				</tbody>
			</table>

			<div class="span1 offset10 label label-info" style="text-align:center">Total : <%= @projets_fermes.count %></div>
		</div>
	</div>
</div>

app/views/projets/new.html.erb
<h1>Nouveau projet</h1>
<br />

<%= render 'form' %>

app/views/projets/show.html.erb
<p class="alert alert-success"><%= notice %></p>

<p>
  <b>Nom : </b>
  <%= @projet.nom %>
</p>

<p>
  <b>Responsable : </b>
  <%= @projet.responsable.nom %>
</p>

<p>
  <b>Pause : </b>
  <%= @projet.pause %>
</p>

<%= link_to("Éditer", edit_projet_path(@projet), :class => "btn btn-primary") %>
<%= link_to("Retour", projets_path, :class => "btn") %>

app/views/responsables/_form.html.erb
<%= form_for(@responsable, :html => { :class => "form-horizontal" }) do |f| %>
<fieldset>
  <% if @responsable.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@responsable.errors.count, "erreur") %> ont été identifiées :</h2>

      <ul>
      <% @responsable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label(:nom, :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:nom, :class => "input-xlarge") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:invalide, :class => "control-label") %>
    <div class="controls">
      <label class="checkbox">
      <%= f.check_box(:invalide) %>
    </div>
  </div>

  <div class="form-actions">
    <% if current_page?(:action => "new") %>
      <%= f.submit("Créer le responsable", :class => "btn btn-primary") %>
	<% else %>
      <%= f.submit("Mettre à jour le responsable", :class => "btn btn-primary") %>
	<% end %>
    <%= link_to("Retour", responsables_path, :class => "btn") %>
  </div>
</fieldset>
<% end %>

app/views/responsables/edit.html.erb
<h1>Modification</h1>
<br />

<%= render 'form' %>

app/views/responsables/index.html.erb
<div class="nouveau">
<%= link_to(new_responsable_path, :class => "btn") do %>
  <i class="icon-edit"></i> Nouveau responsable
<% end %>
</div>

<br>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Nom</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
<% @responsables.each do |responsable| %>
		<tr>
          <% if responsable.invalide == true %>
    		<td class="muted"><%= responsable.nom %></td>
          <% else %>
    		<td><%= responsable.nom %></td>
          <% end %>
    		<td>
				<%= link_to(edit_responsable_path(responsable)) do %><i class="icon-pencil"></i><% end %>
				<%= link_to(responsable, :data => { :confirm => "Cela supprimera définitivement l'entrée !\nÊtes-vous sûr ?" }, :method => :delete) do %><i class="icon-trash"></i><% end %>
			</td>
		</tr>
<% end %>
	</tbody>
</table>

<div class="span1 offset10 label label-info" style="text-align:center">Total : <%= @responsables.count %></div>

app/views/responsables/new.html.erb
<h1>Nouveau responsable</h1>
<br />

<%= render 'form' %>

app/views/responsables/show.html.erb
<p class="alert alert-success"><%= notice %></p>

<p>
  <b>Nom : </b>
  <%= @responsable.nom %>
</p>

<p>
  <b>Invalide : </b>
  <%= @responsable.invalide %>
</p>

<%= link_to("Éditer", edit_responsable_path(@responsable), :class => "btn btn-primary") %>
<%= link_to("Retour", responsables_path, :class => "btn") %>

app/views/taches/_form.html.erb
<%= form_for(@tache, :html => { :class => "form-horizontal" }) do |f| %>
<fieldset>
  <% if @tache.errors.any? %>
    <div class="alert alert-error">
      <h2><%= pluralize(@tache.errors.count, "erreur") %> ont été identifiées :</h2>

      <ul>
      <% @tache.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label(:nom, :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:nom, :class => "input-xlarge") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:projet, :class => "control-label") %>
    <div class="controls">
      <%= f.select(:projet_id, options_from_collection_for_select(Projet.where("pause = 'f'").order("nom"), :id, :nom, @tache.projet_id)) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label("Date de début", :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:date_debut, :class => "datepicker") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label("Date de fin", :class => "control-label") %>
    <div class="controls">
      <%= f.text_field(:date_fin, :class => "datepicker") %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label(:charge, :class => "control-label") %>
    <div class="controls">
      <%= f.select(:charge, [["N/A", 0], ["0,25 j/h", 0.25], ["0,50 j/h", 0.5], ["0,75 j/h", 0.75], ["1,00 j/h", 1], ["1,25 j/h", 1.25], ["1,50 j/h", 1.5], ["1,75 j/h", 1.75], ["2,00 j/h", 2], ["2,25 j/h", 2.25], ["2,50 j/h", 2.5], ["2,75 j/h", 2.75], ["3,00 j/h", 3], ["3,25 j/h", 3.25], ["3,50 j/h", 3.5], ["3,75 j/h", 3.75], ["4,00 j/h", 4], ["4,25 j/h", 4.25], ["4,50 j/h", 4.5], ["4,75 j/h", 4.75], ["5,00 j/h", 5], ["5,25 j/h", 5.25], ["5,50 j/h", 5.5], ["5,75 j/h", 5.75], ["6,00 j/h", 6], ["6,25 j/h", 6.25], ["6,50 j/h", 6.5], ["6,75 j/h", 6.75], ["7,00 j/h", 7], ["7,25 j/h", 7.25], ["7,50 j/h", 7.5], ["7,75 j/h", 7.75], ["8,00 j/h", 8], ["8,25 j/h", 8.25], ["8,50 j/h", 8.5], ["8,75 j/h", 8.75], ["9,00 j/h", 9], ["9,25 j/h", 9.25], ["9,50 j/h", 9.5], ["9,75 j/h", 9.75]]) %>
    </div>
  </div>

  <div class="form-actions">
    <% if current_page?(:action => "new") %>
      <%= f.submit("Créer la tâche", :class => "btn btn-primary") %>
	<% else %>
      <%= f.submit("Mettre à jour la tâche", :class => "btn btn-primary") %>
	<% end %>
    <%= link_to("Retour", taches_path, :class => "btn") %>
  </div>
</fieldset>
<% end %>

app/views/taches/edit.html.erb
<h1>Modification</h1>
<br />

<%= render 'form' %>

app/views/taches/new.html.erb
<h1>Nouvelle tâche</h1>
<br />

<%= render 'form' %>

app/views/taches/show.html.erb
<p class="alert alert-success"><%= notice %></p>

<p>
  <b>Nom : </b>
  <%= @tache.nom %>
</p>

<p>
  <b>Projet : </b>
  <%= @tache.projet.nom %>
</p>

<%= link_to("Éditer", edit_tache_path(@tache), :class => "btn btn-primary") %>
<%= link_to("Retour", taches_path, :class => "btn") %>